// React/light-horizontal/src/pages/account/Confirm.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Redirect, Link } from 'react-router-dom'

import { Container, Row, Col, Card, CardBody, } from 'reactstrap';

import { isUserAuthenticated } from '../../helpers/authUtils';
import logo from '../../assets/images/logo-dark.png';
import mailSvg from '../../assets/images/mail_confirm.png';


class Confirm extends Component {
    _isMounted = false;

    constructor(props) {
        super(props);
        this.state = {
        }
    }

    componentDidMount() {
        this._isMounted = true;
        document.body.classList.add('authentication-bg');
        document.body.classList.add('authentication-bg-pattern');
    }

    componentWillUnmount() {
        this._isMounted = false;
        document.body.classList.remove('authentication-bg');
        document.body.classList.remove('authentication-bg-pattern');
    }

    /**
     * Redirect to root
     */
    renderRedirectToRoot = () => {
        const isAuthTokenValid = isUserAuthenticated();
        if (isAuthTokenValid) {
            return <Redirect to='/' />
        }
    }

    render() {
        const isAuthTokenValid = isUserAuthenticated();
        return (
            <React.Fragment>

                {this.renderRedirectToRoot()}

                {(this._isMounted || !isAuthTokenValid) && <React.Fragment>

                    <div className="account-pages mt-5 mb-5">
                        <Container>
                            <Row className="justify-content-center">
                                <Col md={8} lg={6} xl={5} >
                                    <div className="text-center">
                                        <Link to="/">
                                            <span><img src={logo} alt="" height="22" /></span>
                                        </Link>
                                        <p className="text-muted mt-2 mb-4">Responsive Admin Dashboard</p>
                                    </div>

                                    <Card className="text-center">
                                        <CardBody className="p-4 position-relative">
                                            <div className="mb-4">
                                                <h4 className="text-uppercase mt-0">Confirm Email</h4>
                                            </div>

                                            <img src={mailSvg} alt="img" width="86" className="mx-auto d-block" />

                                            <p className="text-muted font-14 mt-2"> A email has been send to your email.
                                                Please check for an email from company and click on the included link to reset your password. </p>



                                            <p className="text-center">
                                                <Link className="btn btn-block btn-pink waves-effect waves-light mt-3" to="/login">Back to Login</Link>
                                            </p>

                                        </CardBody>
                                    </Card>
                                </Col>
                            </Row>
                        </Container>
                    </div>
                </React.Fragment>}
            </React.Fragment>
        )
    }
}

export default connect()(Confirm);

// Angular/light-vertical/src/app/account/auth/confirm/confirm.component.ts
import { Component, OnInit, AfterViewInit } from '@angular/core';

@Component({
  selector: 'app-confirm',
  templateUrl: './confirm.component.html',
  styleUrls: ['./confirm.component.scss']
})
export class ConfirmComponent implements OnInit, AfterViewInit {

  constructor() { }

  ngOnInit() {
  }

  ngAfterViewInit() {
    document.body.classList.add('authentication-bg');
  }

}

<div class="account-pages mt-5 mb-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-5">
        <div class="text-center">
          <a href="/">
            <span><img src="assets/images/logo-dark.png" alt="" height="22"></span>
          </a>
          <p class="text-muted mt-2 mb-4">Responsive Admin Dashboard</p>
        </div>
        <div class="card text-center">

          <div class="card-body p-4">

            <div class="mb-4">
              <h4 class="text-uppercase mt-0">Confirm Email</h4>
            </div>
            <img src="assets/images/mail_confirm.png" alt="img" width="86" class="mx-auto d-block" />

            <p class="text-muted font-14 mt-2"> A email has been send to your email.
              Please check for an email from company and click on the included link to
              reset your password. </p>

            <a href="/" class="btn btn-block btn-pink waves-effect waves-light mt-3">Back to Home</a>

          </div> <!-- end card-body -->
        </div>
        <!-- end card -->

      </div> <!-- end col -->
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</div>
<!-- end page -->
