// React/light-vertical/src/components/Topbar.js
import React, { Component } from "react";
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';

import NotificationDropdown from './NotificationDropdown';
import ProfileDropdown from './ProfileDropdown';
import logoSm from '../assets/images/logo-sm.png';
import logo from '../assets/images/logo-dark.png';
import profilePic from '../assets/images/users/user-1.jpg';


const Notifications = [{
  id: 1,
  text: 'Caleb Flakelar commented on Admin',
  subText: '1 min ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'primary'
},
{
  id: 2,
  text: 'New user registered.',
  subText: '5 min ago',
  icon: 'mdi mdi-account-plus',
  bgColor: 'info'
},
{
  id: 3,
  text: 'Cristina Pride',
  subText: 'Hi, How are you? What about our next meeting',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'success'
},
{
  id: 4,
  text: 'Caleb Flakelar commented on Admin',
  subText: '2 days ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'danger'
},
{
  id: 5,
  text: 'Caleb Flakelar commented on Admin',
  subText: '1 min ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'primary'
},
{
  id: 6,
  text: 'New user registered.',
  subText: '5 min ago',
  icon: 'mdi mdi-account-plus',
  bgColor: 'info'
},
{
  id: 7,
  text: 'Cristina Pride',
  subText: 'Hi, How are you? What about our next meeting',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'success'
},
{
  id: 8,
  text: 'Caleb Flakelar commented on Admin',
  subText: '2 days ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'danger'
}];

const ProfileMenus = [{
  label: 'My Account',
  icon: 'fe-user',
  redirectTo: "/",
},
{
  label: 'Settings',
  icon: 'fe-settings',
  redirectTo: "/"
},
{
  label: 'Lock Screen',
  icon: 'fe-lock',
  redirectTo: "/"
},
{
  label: 'Logout',
  icon: 'fe-log-out',
  redirectTo: "/logout",
  hasDivider: true
}]


class Topbar extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }


  render() {
    return (
      <React.Fragment>
        <div className="navbar-custom">
          <ul className="list-unstyled topnav-menu float-right mb-0">

            <li className="d-none d-sm-block">
              <form className="app-search">
                <div className="app-search-box">
                  <div className="input-group">
                    <input type="text" className="form-control" placeholder="Search..." />
                    <div className="input-group-append">
                      <button className="btn" type="submit">
                        <i className="fe-search"></i>
                      </button>
                    </div>
                  </div>
                </div>
              </form>
            </li>

            <li>
              <NotificationDropdown notifications={Notifications} />
            </li>

            <li>
              <ProfileDropdown profilePic={profilePic} menuItems={ProfileMenus} username={'Nik Patel'} />
            </li>


            <li className="dropdown notification-list">
              <button className="btn btn-link nav-link right-bar-toggle waves-effect waves-light" onClick={this.props.rightSidebarToggle}>
                <i className="fe-settings noti-icon"></i>
              </button>
            </li>
          </ul>

          <div className="logo-box">
            <Link to="/" className="logo text-center">
              <span className="logo-lg">
                <img src={logo} alt="" height="16" />
              </span>
              <span className="logo-sm">
                <img src={logoSm} alt="" height="24" />
              </span>
            </Link>
          </div>

          <ul className="list-unstyled topnav-menu topnav-menu-left m-0">
            <li>
              <button className="button-menu-mobile disable-btn waves-effect" onClick={this.props.menuToggle}>
                <i className="fe-menu"></i>
              </button>
            </li>

            <li>
              <h4 className="page-title-main">{this.props.title}</h4>
            </li>
          </ul>
            
        </div>
      </React.Fragment >
    );
  }
}


export default connect()(Topbar);

// Angular/light-vertical/src/app/layouts/topbar/topbar.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { EventService } from '../../core/services/event.service';
import { AuthenticationService } from '../../core/services/auth.service';


@Component({
  selector: 'app-topbar',
  templateUrl: './topbar.component.html',
  styleUrls: ['./topbar.component.scss']
})
export class TopbarComponent implements OnInit {
  pageHeading: string;
  notificationItems: Array<{}>;
  openMobileMenu: boolean;

  @Output() settingsButtonClicked = new EventEmitter();
  @Output() mobileMenuButtonClicked = new EventEmitter();

  constructor(private router: Router, private authService: AuthenticationService, private eventService: EventService) {}

  ngOnInit() {
    // get the notifications
    this._fetchNotifications();
    this.openMobileMenu = false;

    this.eventService.subscribe('changePageHeading', (heading) => {
      this.pageHeading = heading;
    });
  }

  /**
   * Toggles the right sidebar
   */
  toggleRightSidebar() {
    this.settingsButtonClicked.emit();
  }

  /**
   * Toggle the menu bar when having mobile screen
   */
  toggleMobileMenu(event: any) {
    event.preventDefault();
    this.mobileMenuButtonClicked.emit();
  }

  /**
   * Logout the user
   */
  logout() {
    this.authService.logout();
    this.router.navigate(['/account/login']);
  }

  /**
   * Fetches the notification
   * Note: For now returns the hard coded notifications
   */
  _fetchNotifications() {
    this.notificationItems = [{
      text: 'Caleb Flakelar commented on Admin',
      subText: '1 min ago',
      icon: 'mdi mdi-comment-account-outline',
      bgColor: 'primary',
      redirectTo: '/notification/1'
    },
    {
      text: 'New user registered.',
      subText: '5 min ago',
      icon: 'mdi mdi-account-plus',
      bgColor: 'info',
      redirectTo: '/notification/2'
    },
    {
      text: 'Cristina Pride',
      subText: 'Hi, How are you? What about our next meeting',
      icon: 'mdi mdi-comment-account-outline',
      bgColor: 'success',
      redirectTo: '/notification/3'
    },
    {
      text: 'Caleb Flakelar commented on Admin',
      subText: '2 days ago',
      icon: 'mdi mdi-comment-account-outline',
      bgColor: 'danger',
      redirectTo: '/notification/4'
    },
    {
      text: 'Caleb Flakelar commented on Admin',
      subText: '1 min ago',
      icon: 'mdi mdi-comment-account-outline',
      bgColor: 'primary',
      redirectTo: '/notification/5'
    },
    {
      text: 'New user registered.',
      subText: '5 min ago',
      icon: 'mdi mdi-account-plus',
      bgColor: 'info',
      redirectTo: '/notification/6'
    },
    {
      text: 'Cristina Pride',
      subText: 'Hi, How are you? What about our next meeting',
      icon: 'mdi mdi-comment-account-outline',
      bgColor: 'success',
      redirectTo: '/notification/7'
    },
    {
      text: 'Caleb Flakelar commented on Admin',
      subText: '2 days ago',
      icon: 'mdi mdi-comment-account-outline',
      bgColor: 'danger',
      redirectTo: '/notification/8'
    }];
  }
}

<!-- Topbar Start -->
<div class="navbar-custom">
  <ul class="list-unstyled topnav-menu float-right mb-0">

    <li class="d-none d-sm-block">
      <form class="app-search">
        <div class="app-search-box">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search...">
            <div class="input-group-append">
              <button class="btn" type="submit">
                <i class="fe-search"></i>
              </button>
            </div>
          </div>
        </div>
      </form>
    </li>

    <li class="dropdown notification-list" ngbDropdown>
      <a class="nav-link dropdown-toggle  waves-effect waves-light" href="javascript: void(0);" role="button"
        aria-haspopup="false" aria-expanded="false" ngbDropdownToggle id="notificationDropdown">
        <i class="fe-bell noti-icon"></i>
        <span class="badge badge-danger rounded-circle noti-icon-badge">4</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg"
        aria-labelledby="notificationDropdown" ngbDropdownMenu>

        <!-- item-->
        <div class="dropdown-item noti-title" ngbDropdownItem>
          <h5 class="m-0">
            <span class="float-right">
              <a href="javascript: void(0);" class="text-dark">
                <small>Clear All</small>
              </a>
            </span>Notification
          </h5>
        </div>

        <div id="notification-items" class="slimscroll noti-scroll" appSlimScroll>
          <!-- item-->
          <a *ngFor="let notification of notificationItems;" href="{{ notification.redirectTo }}"
            class="dropdown-item notify-item" ngbDropdownItem>
            <div class="notify-icon bg-soft-{{ notification.bgColor }} text-{{ notification.bgColor }}">
              <i class="{{ notification.icon }}"></i>
            </div>
            <p class="notify-details">{{ notification.text }}
              <small class="text-muted">{{ notification.subText }}</small>
            </p>
          </a>
        </div>

        <!-- All-->
        <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
          View All
        </a>
      </div>
    </li>


    <li class="dropdown notification-list" ngbDropdown>
      <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" ngbDropdownToggle id="profileDropdown"
        href="javascript: void(0);" role="button" aria-haspopup="false" aria-expanded="false">
        <img src="assets/images/users/user-1.jpg" alt="user-image" class="rounded-circle">
        <span class="pro-user-name ml-1">
          Nik Patel <i class="mdi mdi-chevron-down"></i>
        </span>
      </a>
      <div class="dropdown-menu dropdown-menu-right profile-dropdown" aria-labelledby="profileDropdown" ngbDropdownMenu>
        <div class="dropdown-header noti-title">
          <h6 class="text-overflow m-0">Welcome !</h6>
        </div>

        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item notify-item">
          <i class="fe-user"></i>
          <span>My Account</span>
        </a>

        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item notify-item">
          <i class="fe-settings"></i>
          <span>Settings</span>
        </a>

        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item notify-item">
          <i class="fe-lock"></i>
          <span>Lock Screen</span>
        </a>

        <div class="dropdown-divider"></div>

        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item notify-item" (click)="logout()">
          <i class="fe-log-out"></i>
          <span>Logout</span>
        </a>

      </div>
    </li>


    <li class="dropdown notification-list">
      <a href="javascript:void(0);" class="nav-link right-bar-toggle waves-effect waves-light"
        (click)="toggleRightSidebar()">
        <i class="fe-settings noti-icon"></i>
      </a>
    </li>


  </ul>

  <!-- LOGO -->
  <div class="logo-box">
    <a href="/" class="logo text-center">
      <span class="logo-lg">
        <img src="assets/images/logo-dark.png" alt="" height="16">
        <!-- <span class="logo-lg-text-light">Xeria</span> -->
      </span>
      <span class="logo-sm">
        <!-- <span class="logo-sm-text-dark">X</span> -->
        <img src="assets/images/logo-sm.png" alt="" height="24">
      </span>
    </a>
  </div>

  <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
    <li>
      <button class="button-menu-mobile disable-btn waves-effect" (click)="toggleMobileMenu($event)">
        <i class="fe-menu"></i>
      </button>
    </li>

    <li>
      <h4 class="page-title-main">{{pageHeading}}</h4>
    </li>

  </ul>
</div>
<!-- end Topbar -->
